### ISSUE TITLE
Login from Specific User Profile Times Out

### ISSUE THREAD

**Issue by sydlexius** [MediaBrowser/MediaBrowser.Classic#261]
Just a quick note that I seem to recall this starting around 3.0.244.  I am unable to roll back to anything earlier to see if this behavior goes away.

My MBS is configured with three profiles.  For the troublesome profile in specific, when I select it at the login screen, the six dots will stay on the screen until one of two things happens: Either the MBC Screensaver kicks in, or I restart MBS (both are on the same machine).  This profile works fine via MBT on all my machines, the ModernUI app, Android, iOS, Roku, and web.  I even went so far as to use config backup to migrate only my playstate to a new profile, only to see it happen again.

Please let me know which debug settings I need to enable, or which log files I need to capture.  I ran a tail -f on both the MBS and MBC logs, and didn't see anything obvious.

**Comment by ebr11** [comment]
Please create a post on the forum and attach the MBC log from when this happens.  Thanks.

**Comment by sydlexius** [comment]
Currently my whole setup is still boxed up from my recent move.

**Comment by ebr11** [comment]
Closing until can be reproduced.

**Comment by sydlexius** [comment]
That's fine. I just finished building a new machine, and restored a backup.
So far, it hasn't manifested.
