### ISSUE TITLE
Port PlaybackManager

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.Classic#265]
Found here:

https://github.com/MediaBrowser/MediaBrowser.ApiClient/blob/master/MediaBrowser.ApiInteraction/Playback/PlaybackManager.cs

It has some new stuff that MBC isn't currently doing like pulling down media sources right at the time of Playback. It also encapsulates all of the pre and post playback actions that need to occur. I was going to open a similar issue as this:

https://github.com/MediaBrowser/MediaBrowser.WindowsRT/issues/69

But it's not possible since you don't have a PlaybackManager. But if you were to port it and put it in it's own separate class, then I can try to make future changes to it myself.

**Comment by ebr11** [comment]
I'm sure this would be beneficial but not something I'm willing to take on right now.

Playback is a bit of a black box with a lot of (over) complicated parts.  I know if I open that box it will take me weeks to get playback working properly again - similar to the library views I just spent a bunch of time on.

I'll keep it here on the plate for now.
