### ISSUE TITLE
Specify ItemCounts field if needed

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.Classic#272]
When you query for People, Artists, Genres, or Studios, the server dynamically counts the number of media for each one returned, e.g movie count for genres, etc.

If you are using these counts, add ItemCounts to the fields requested. If you are not using these counts, then close this ticket. 

The information is being returned by default but it is causing performance issues and needs to be changed opt-in in a future sever release.

**Comment by ebr11** [comment]
Shouldn't be needed
